In [2]:
import pandas as pd

In [10]:
data = pd.read_csv('E:\\data\\fresh_comp_offline\\tianchi_fresh_comp_train_user.csv')

In [4]:
#print(data)

           user_id    item_id  behavior_type user_geohash  item_category  \
0         10001082  285259775              1      97lk14c           4076
1         10001082    4368907              1          NaN           5503
2         10001082    4368907              1          NaN           5503
3         10001082   53616768              1          NaN           9762
4         10001082  151466952              1          NaN           5232
5         10001082   53616768              4          NaN           9762
6         10001082  290088061              1          NaN           5503
7         10001082  298397524              1          NaN          10894
8         10001082   32104252              1          NaN           6513
9         10001082  323339743              1          NaN          10894
10        10001082  396795886              1          NaN           2825
11        10001082    9947871              1          NaN           2825
12        10001082  150720867              1      95qoghe           3200
13        10001082  275221686              1          NaN          10576
14        10001082   97441652              1          NaN          10576
15        10001082  275221686              1          NaN          10576
16        10001082  275221686              1          NaN          10576
17        10001082  220586551              1          NaN           7079
18        10001082  296378545              1          NaN           6669
19        10001082  266563343              1      95qobus           5232
20        10001082  151466952              1          NaN           5232
21        10001082  209290607              1          NaN           5894
22        10001082  296378545              1          NaN           6669
23        10001082   22667958              1      95qogn4          10523
24        10001082  125083630              1          NaN           4722
25        10001082  236453039              1          NaN          10576
26        10001082  282931871              1          NaN           6000
27        10001082  266188611              1          NaN          10223
28        10001082  302705570              1          NaN          10894
29        10001082   45258196              1          NaN           5894
...            ...        ...            ...          ...            ...
1048545  111699844  359110623              1          NaN           5894
1048546  111699844  362439123              1      9rnhf0e           6513
1048547  111699844   19610862              1      9rnhfvr          13332
1048548  111699844   90716322              1          NaN          13332
1048549  111699844   77880406              1          NaN          12479
1048550  111699844   74513978              1      9rnhfv7           1083
1048551  111699844  151212664              1          NaN          13332
1048552  111699844   15625013              1          NaN          10250
1048553  111699844   20041202              1          NaN           6513
1048554  111699844  147758858              2          NaN           5503
1048555  111699844   90178311              1          NaN          12479
1048556  111699844   89496497              1      9rnhf1g           9130
1048557  111699844  160950160              1      9rnhfv2           9130
1048558  111699844  367665404              1          NaN           9179
1048559  111699844  273076274              1          NaN           6513
1048560  111699844   18376823              1          NaN           3975
1048561  111699844   79936102              1          NaN          11241
1048562  111699844   51945560              1          NaN           8665
1048563  111699844  273867316              1          NaN           5503
1048564  111699844  222421477              1      9rnhfu7           7297
1048565  111699844  282527574              1          NaN           7297
1048566  111699844  146173654              1          NaN           9540
1048567  111699844   87680984              1          NaN           5689
1048568  111699844  102969825              1          NaN          11622
1048569  111699844  128214996              1          NaN           1863
1048570  111699844  248710633              1          NaN          11454
1048571  111699844  315280755              1      9rnhfu7          13727
1048572  111699844  282237180              1      9rnhf0g           9130
1048573  111699844  156703359              1          NaN           2825
1048574  111699844  195157416              1          NaN           1863

                  time
0        2014-12-08 18
1        2014-12-12 12
2        2014-12-12 12
3        2014-12-02 15
4        2014-12-12 11
5        2014-12-02 15
6        2014-12-12 12
7        2014-12-12 12
8        2014-12-12 12
9        2014-12-12 12
10       2014-12-12 12
11       2014-11-28 20
12       2014-12-15 08
13       2014-12-03 01
14       2014-11-20 21
15       2014-12-13 14
16       2014-12-08 07
17       2014-12-14 03
18       2014-12-02 12
19       2014-12-12 11
20       2014-12-12 11
21       2014-12-14 16
22       2014-12-02 12
23       2014-12-15 08
24       2014-12-14 03
25       2014-12-08 07
26       2014-12-10 13
27       2014-11-20 19
28       2014-12-12 12
29       2014-12-12 12
...                ...
1048545  2014-11-24 18
1048546  2014-11-30 11
1048547  2014-11-23 11
1048548  2014-11-21 10
1048549  2014-11-28 19
1048550  2014-12-13 21
1048551  2014-11-21 10
1048552  2014-11-18 23
1048553  2014-11-23 19
1048554  2014-11-19 11
1048555  2014-11-28 22
1048556  2014-12-13 22
1048557  2014-12-13 22
1048558  2014-11-21 16
1048559  2014-11-30 13
1048560  2014-11-21 17
1048561  2014-11-27 12
1048562  2014-11-29 19
1048563  2014-11-21 11
1048564  2014-12-14 13
1048565  2014-11-27 12
1048566  2014-11-25 15
1048567  2014-11-25 19
1048568  2014-11-26 10
1048569  2014-11-28 23
1048570  2014-11-19 16
1048571  2014-12-14 13
1048572  2014-12-13 22
1048573  2014-11-29 22
1048574  2014-11-26 08

[1048575 rows x 6 columns]

In [11]:
print(data.shape)
del data['user_geohash']
del data['item_category']
print(data)

(1048575, 6)
           user_id    item_id  behavior_type           time
0         10001082  285259775              1  2014-12-08 18
1         10001082    4368907              1  2014-12-12 12
2         10001082    4368907              1  2014-12-12 12
3         10001082   53616768              1  2014-12-02 15
4         10001082  151466952              1  2014-12-12 11
5         10001082   53616768              4  2014-12-02 15
6         10001082  290088061              1  2014-12-12 12
7         10001082  298397524              1  2014-12-12 12
8         10001082   32104252              1  2014-12-12 12
9         10001082  323339743              1  2014-12-12 12
10        10001082  396795886              1  2014-12-12 12
11        10001082    9947871              1  2014-11-28 20
12        10001082  150720867              1  2014-12-15 08
13        10001082  275221686              1  2014-12-03 01
14        10001082   97441652              1  2014-11-20 21
15        10001082  275221686              1  2014-12-13 14
16        10001082  275221686              1  2014-12-08 07
17        10001082  220586551              1  2014-12-14 03
18        10001082  296378545              1  2014-12-02 12
19        10001082  266563343              1  2014-12-12 11
20        10001082  151466952              1  2014-12-12 11
21        10001082  209290607              1  2014-12-14 16
22        10001082  296378545              1  2014-12-02 12
23        10001082   22667958              1  2014-12-15 08
24        10001082  125083630              1  2014-12-14 03
25        10001082  236453039              1  2014-12-08 07
26        10001082  282931871              1  2014-12-10 13
27        10001082  266188611              1  2014-11-20 19
28        10001082  302705570              1  2014-12-12 12
29        10001082   45258196              1  2014-12-12 12
...            ...        ...            ...            ...
1048545  111699844  359110623              1  2014-11-24 18
1048546  111699844  362439123              1  2014-11-30 11
1048547  111699844   19610862              1  2014-11-23 11
1048548  111699844   90716322              1  2014-11-21 10
1048549  111699844   77880406              1  2014-11-28 19
1048550  111699844   74513978              1  2014-12-13 21
1048551  111699844  151212664              1  2014-11-21 10
1048552  111699844   15625013              1  2014-11-18 23
1048553  111699844   20041202              1  2014-11-23 19
1048554  111699844  147758858              2  2014-11-19 11
1048555  111699844   90178311              1  2014-11-28 22
1048556  111699844   89496497              1  2014-12-13 22
1048557  111699844  160950160              1  2014-12-13 22
1048558  111699844  367665404              1  2014-11-21 16
1048559  111699844  273076274              1  2014-11-30 13
1048560  111699844   18376823              1  2014-11-21 17
1048561  111699844   79936102              1  2014-11-27 12
1048562  111699844   51945560              1  2014-11-29 19
1048563  111699844  273867316              1  2014-11-21 11
1048564  111699844  222421477              1  2014-12-14 13
1048565  111699844  282527574              1  2014-11-27 12
1048566  111699844  146173654              1  2014-11-25 15
1048567  111699844   87680984              1  2014-11-25 19
1048568  111699844  102969825              1  2014-11-26 10
1048569  111699844  128214996              1  2014-11-28 23
1048570  111699844  248710633              1  2014-11-19 16
1048571  111699844  315280755              1  2014-12-14 13
1048572  111699844  282237180              1  2014-12-13 22
1048573  111699844  156703359              1  2014-11-29 22
1048574  111699844  195157416              1  2014-11-26 08

[1048575 rows x 4 columns]

In [14]:
time = data['time']
print(time[0].split())

AttributeError: 'str' object has no attribute 'type'